version: '3.8'
services:
  backend:
    build: ./backend
    image: 434000704945.dkr.ecr.eu-north-1.amazonaws.com/myapp-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=...  # adjust
      - DB_USER=...
      - DB_PASS=...
  frontend:
    build: ./frontend
    image: 434000704945.dkr.ecr.eu-north-1.amazonaws.com/myapp-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend